insert into Customer (ID, FIRST_NAME, LAST_NAME, EMAIL, MOBILE, JOB) values (1, 'Gibby', 'Fishley', 'gfishley0@sun.com', '208-485-4364', 'Payment Adjustment Coordinator');
insert into Customer (ID, FIRST_NAME, LAST_NAME, EMAIL, MOBILE, JOB) values (2, 'Marcos', 'Wimlett', 'mwimlett1@bing.com', '988-700-4794', 'VP Quality Control');
insert into Customer (ID, FIRST_NAME, LAST_NAME, EMAIL, MOBILE, JOB) values (3, 'Benoite', 'Braney', 'bbraney2@europa.eu', '452-684-7734', 'Junior Executive');
insert into Customer (ID, FIRST_NAME, LAST_NAME, EMAIL, MOBILE, JOB) values (4, 'Ingrid', 'Dislee', 'idislee3@seattletimes.com', '832-343-6939', 'Mechanical Systems Engineer');
insert into Customer (ID, FIRST_NAME, LAST_NAME, EMAIL, MOBILE, JOB) values (5, 'Willis', 'Reeders', 'wreeders4@businessinsider.com', '592-354-4853', 'Tax Accountant');
insert into Customer (ID, FIRST_NAME, LAST_NAME, EMAIL, MOBILE, JOB) values (6, 'Raddy', 'Gillio', 'rgillio5@over-blog.com', '935-615-9383', 'Marketing Manager');
insert into Customer (ID, FIRST_NAME, LAST_NAME, EMAIL, MOBILE, JOB) values (7, 'Fancie', 'Hazard', 'fhazard6@com.com', '783-544-5247', 'Physical Therapy Assistant');
insert into Customer (ID, FIRST_NAME, LAST_NAME, EMAIL, MOBILE, JOB) values (8, 'Phillipe', 'Housego', 'phousego7@cnbc.com', '679-513-6677', 'Programmer I');
insert into Customer (ID, FIRST_NAME, LAST_NAME, EMAIL, MOBILE, JOB) values (9, 'Clim', 'McGriffin', 'cmcgriffin8@sohu.com', '774-461-7760', 'Physical Therapy Assistant');
insert into Customer (ID, FIRST_NAME, LAST_NAME, EMAIL, MOBILE, JOB) values (10, 'Ammamaria', 'Copozio', 'acopozio9@home.pl', '775-170-3467', 'Staff Scientist');
insert into Customer (ID, FIRST_NAME, LAST_NAME, EMAIL, MOBILE, JOB) values (11, 'Bennie', 'Grimmer', 'bgrimmera@ovh.net', '552-129-2483', 'VP Product Management');
insert into Customer (ID, FIRST_NAME, LAST_NAME, EMAIL, MOBILE, JOB) values (12, 'Starlene', 'Verrico', 'sverricob@microsoft.com', '724-489-1346', 'Food Chemist');
insert into Customer (ID, FIRST_NAME, LAST_NAME, EMAIL, MOBILE, JOB) values (13, 'Izak', 'Gerold', 'igeroldc@comsenz.com', '717-995-1781', 'Senior Sales Associate');
insert into Customer (ID, FIRST_NAME, LAST_NAME, EMAIL, MOBILE, JOB) values (14, 'Denyse', 'Copnall', 'dcopnalld@parallels.com', '612-221-9936', 'Associate Professor');
insert into Customer (ID, FIRST_NAME, LAST_NAME, EMAIL, MOBILE, JOB) values (15, 'Nertie', 'Thornton-Dewhirst', 'nthorntondewhirste@umn.edu', '942-975-7816', 'Account Coordinator');
insert into Customer (ID, FIRST_NAME, LAST_NAME, EMAIL, MOBILE, JOB) values (16, 'Egon', 'Stansfield', 'estansfieldf@cornell.edu', '455-843-7853', 'Sales Representative');
insert into Customer (ID, FIRST_NAME, LAST_NAME, EMAIL, MOBILE, JOB) values (17, 'Eunice', 'Tremonte', 'etremonteg@amazon.de', '934-789-8214', 'Human Resources Assistant IV');
insert into Customer (ID, FIRST_NAME, LAST_NAME, EMAIL, MOBILE, JOB) values (18, 'Oliviero', 'Hamill', 'ohamillh@spiegel.de', '423-683-0092', 'Junior Executive');
insert into Customer (ID, FIRST_NAME, LAST_NAME, EMAIL, MOBILE, JOB) values (19, 'Scarlett', 'Merricks', 'smerricksi@fda.gov', '989-594-8097', 'VP Accounting');
insert into Customer (ID, FIRST_NAME, LAST_NAME, EMAIL, MOBILE, JOB) values (20, 'Lu', 'Stoter', 'lstoterj@booking.com', '796-653-8401', 'Registered Nurse');
