insert into product (id, name, brand, made_in, price) values (1, 'Oil - Margarine', 'Altenwerth LLC', 'United States', 997.73);
insert into product (id, name, brand, made_in, price) values (2, 'Lid - Translucent, 3.5 And 6 Oz', 'Heller Inc', 'China', 567.88);
insert into product (id, name, brand, made_in, price) values (3, 'Cardamon Seed / Pod', 'Nikolaus, Kunze and Lakin', 'Philippines', 295.34);
insert into product (id, name, brand, made_in, price) values (4, 'Southern Comfort', 'Mills, Russel and Parker', 'Nigeria', 414.25);
insert into product (id, name, brand, made_in, price) values (5, 'Catfish - Fillets', 'Moore-VonRueden', 'Sweden', 988.61);
insert into product (id, name, brand, made_in, price) values (6, 'Goat - Leg', 'Bartoletti, Graham and Dietrich', 'China', 465.57);
insert into product (id, name, brand, made_in, price) values (7, 'Chinese Foods - Chicken Wing', 'Considine-Farrell', 'China', 794.19);
insert into product (id, name, brand, made_in, price) values (8, 'Nut - Pumpkin Seeds', 'Dickens-Sipes', 'China', 645.42);
insert into product (id, name, brand, made_in, price) values (9, 'Pie Shells 10', 'Ferry-Koch', 'Costa Rica', 841.87);
insert into product (id, name, brand, made_in, price) values (10, 'Iced Tea Concentrate', 'Bailey Inc', 'Tanzania', 102.56);
insert into product (id, name, brand, made_in, price) values (11, 'Extract - Lemon', 'Vandervort-Hettinger', 'Croatia', 655.25);
insert into product (id, name, brand, made_in, price) values (12, 'Onions - Red Pearl', 'Morissette-Erdman', 'Indonesia', 706.93);
insert into product (id, name, brand, made_in, price) values (13, 'Asparagus - Mexican', 'Altenwerth Inc', 'Indonesia', 818.73);
insert into product (id, name, brand, made_in, price) values (14, 'Pastry - Carrot Muffin - Mini', 'Hayes-Nicolas', 'Peru', 264.85);
insert into product (id, name, brand, made_in, price) values (15, 'Lamb - Pieces, Diced', 'Murphy, Crist and Schowalter', 'Indonesia', 954.94);
insert into product (id, name, brand, made_in, price) values (16, 'Mustard - Dry, Powder', 'Weissnat-Erdman', 'United States', 978.77);
insert into product (id, name, brand, made_in, price) values (17, 'Extract - Almond', 'Stehr, Goodwin and Rosenbaum', 'France', 757.32);
insert into product (id, name, brand, made_in, price) values (18, 'Water - Perrier', 'Goldner, Shanahan and Rolfson', 'Czech Republic', 368.42);
insert into product (id, name, brand, made_in, price) values (19, 'Cheese - Boursin, Garlic / Herbs', 'Krajcik Group', 'Mali', 935.46);
insert into product (id, name, brand, made_in, price) values (20, 'Tomato - Green', 'Klocko-Flatley', 'China', 912.11);
insert into product (id, name, brand, made_in, price) values (21, 'Sprouts - Corn', 'Luettgen-Schmidt', 'Russia', 575.74);
insert into product (id, name, brand, made_in, price) values (22, 'Red Currant Jelly', 'Hamill, Huel and Langosh', 'Sweden', 496.74);
insert into product (id, name, brand, made_in, price) values (23, 'Grapes - Green', 'Luettgen Inc', 'China', 141.83);
insert into product (id, name, brand, made_in, price) values (24, 'Flour - Rye', 'Gleason, Abshire and Kiehn', 'China', 932.46);
insert into product (id, name, brand, made_in, price) values (25, 'Iced Tea - Lemon, 340ml', 'Crist, Wisozk and Stanton', 'Azerbaijan', 684.41);
insert into product (id, name, brand, made_in, price) values (26, 'Appetizer - Crab And Brie', 'Howell, Jacobson and Kautzer', 'Poland', 751.32);
insert into product (id, name, brand, made_in, price) values (27, 'Pastry - Chocolate Marble Tea', 'Walker and Sons', 'France', 348.62);
insert into product (id, name, brand, made_in, price) values (28, 'Wine - Prosecco Valdobiaddene', 'Kuphal Group', 'Thailand', 234.11);
insert into product (id, name, brand, made_in, price) values (29, 'Bread - Focaccia Quarter', 'Stiedemann Inc', 'Philippines', 301.79);
insert into product (id, name, brand, made_in, price) values (30, 'Soupcontfoam16oz 116con', 'Bradtke, Feil and Bergnaum', 'United States', 848.58);
insert into product (id, name, brand, made_in, price) values (31, 'Energy Drink Red Bull', 'Turcotte-Crist', 'China', 348.52);
insert into product (id, name, brand, made_in, price) values (32, 'Skirt - 24 Foot', 'Gusikowski Inc', 'Peru', 341.04);
insert into product (id, name, brand, made_in, price) values (33, 'Lamb - Whole Head Off', 'Raynor-Kovacek', 'Indonesia', 164.8);
insert into product (id, name, brand, made_in, price) values (34, 'Bread - French Stick', 'Nienow-Walker', 'China', 327.37);
insert into product (id, name, brand, made_in, price) values (35, 'Peppercorns - Green', 'Kassulke-Konopelski', 'Kazakhstan', 524.09);
insert into product (id, name, brand, made_in, price) values (36, 'Bread - Ciabatta Buns', 'Aufderhar, Wunsch and Botsford', 'China', 337.89);
insert into product (id, name, brand, made_in, price) values (37, 'Wine - White, French Cross', 'Nader Inc', 'Brazil', 776.34);
insert into product (id, name, brand, made_in, price) values (38, 'Butcher Twine 4r', 'Kuhn LLC', 'Poland', 750.44);
insert into product (id, name, brand, made_in, price) values (39, 'Vinegar - Tarragon', 'Luettgen-Leuschke', 'China', 52.51);
insert into product (id, name, brand, made_in, price) values (40, 'Tequila - Sauza Silver', 'Lesch, Purdy and Hudson', 'Greece', 681.44);
insert into product (id, name, brand, made_in, price) values (41, 'Herb Du Provence - Primerba', 'McKenzie-Kuhic', 'China', 634.02);
insert into product (id, name, brand, made_in, price) values (42, 'Lid Tray - 12in Dome', 'Lehner and Sons', 'Indonesia', 580.68);
insert into product (id, name, brand, made_in, price) values (43, 'Sugar - Invert', 'Hoeger, Friesen and Kuhlman', 'China', 738.79);
insert into product (id, name, brand, made_in, price) values (44, 'Pasta - Canelloni', 'Grimes LLC', 'Indonesia', 598.79);
insert into product (id, name, brand, made_in, price) values (45, 'Skirt - 24 Foot', 'Schimmel, Robel and Ruecker', 'Nigeria', 407.82);
insert into product (id, name, brand, made_in, price) values (46, 'Beans - Soya Bean', 'Torp Inc', 'Egypt', 589.74);
insert into product (id, name, brand, made_in, price) values (47, 'Juice - Orange, Concentrate', 'Kuphal and Sons', 'Japan', 39.83);
insert into product (id, name, brand, made_in, price) values (48, 'Beef - Ground, Extra Lean, Fresh', 'Heidenreich LLC', 'Serbia', 60.45);
insert into product (id, name, brand, made_in, price) values (49, 'Melon - Watermelon, Seedless', 'Jast LLC', 'Armenia', 501.33);
insert into product (id, name, brand, made_in, price) values (50, 'Wine - Kwv Chenin Blanc South', 'Shanahan, Glover and Zemlak', 'Macedonia', 73.43);
insert into product (id, name, brand, made_in, price) values (51, 'Bok Choy - Baby', 'Bednar, Littel and Kutch', 'Portugal', 487.37);
insert into product (id, name, brand, made_in, price) values (52, 'Coffee Cup 12oz 5342cd', 'Wiegand Inc', 'Philippines', 965.65);
insert into product (id, name, brand, made_in, price) values (53, 'Lemon Grass', 'O''Kon Group', 'Indonesia', 737.24);
insert into product (id, name, brand, made_in, price) values (54, 'Towel - Roll White', 'Hirthe and Sons', 'Ukraine', 467.41);
insert into product (id, name, brand, made_in, price) values (55, 'Spice - Chili Powder Mexican', 'Kling-Cormier', 'Peru', 55.4);
insert into product (id, name, brand, made_in, price) values (56, 'Filling - Mince Meat', 'Koss and Sons', 'Ukraine', 21.75);
insert into product (id, name, brand, made_in, price) values (57, 'Beets', 'Schuppe, VonRueden and Leffler', 'Thailand', 386.07);
insert into product (id, name, brand, made_in, price) values (58, 'Eggroll', 'Jakubowski, Bode and Schaefer', 'Afghanistan', 743.31);
insert into product (id, name, brand, made_in, price) values (59, 'Beef - Tongue, Fresh', 'Kozey-Watsica', 'United States', 544.58);
insert into product (id, name, brand, made_in, price) values (60, 'Artichokes - Jerusalem', 'Hayes-Wiza', 'China', 316.96);
insert into product (id, name, brand, made_in, price) values (61, 'Pork - Loin, Center Cut', 'Beer-Langosh', 'Yemen', 184.8);
insert into product (id, name, brand, made_in, price) values (62, 'Lamb - Loin Chops', 'DuBuque, Rippin and Schinner', 'Argentina', 463.23);
insert into product (id, name, brand, made_in, price) values (63, 'Wine - Barolo Fontanafredda', 'Gottlieb-Predovic', 'Brazil', 944.94);
insert into product (id, name, brand, made_in, price) values (64, 'Vaccum Bag - 14x20', 'Weimann Group', 'Philippines', 828.57);
insert into product (id, name, brand, made_in, price) values (65, 'Syrup - Monin, Swiss Choclate', 'Harris-Hackett', 'France', 803.16);
insert into product (id, name, brand, made_in, price) values (66, 'Brandy Cherry - Mcguinness', 'Kozey-Cruickshank', 'Indonesia', 220.22);
insert into product (id, name, brand, made_in, price) values (67, 'Pork - Back, Short Cut, Boneless', 'Williamson-Reichel', 'East Timor', 809.4);
insert into product (id, name, brand, made_in, price) values (68, 'Vodka - Hot, Lnferno', 'Robel-Crist', 'Cyprus', 385.62);
insert into product (id, name, brand, made_in, price) values (69, 'Long Island Ice Tea', 'Schowalter LLC', 'South Africa', 700.18);
insert into product (id, name, brand, made_in, price) values (70, 'Wine - Two Oceans Cabernet', 'Yundt-Kuvalis', 'El Salvador', 299.72);
insert into product (id, name, brand, made_in, price) values (71, 'Oil - Truffle, White', 'McGlynn and Sons', 'Greece', 789.29);
insert into product (id, name, brand, made_in, price) values (72, 'Coconut - Shredded, Sweet', 'Kuphal, Connelly and Schaden', 'Croatia', 293.36);
insert into product (id, name, brand, made_in, price) values (73, 'Pork - Liver', 'Goodwin LLC', 'Jordan', 975.45);
insert into product (id, name, brand, made_in, price) values (74, 'Bread Bowl Plain', 'Ondricka-Zulauf', 'Slovenia', 427.07);
insert into product (id, name, brand, made_in, price) values (75, 'Beef - Texas Style Burger', 'Halvorson-Smith', 'Greece', 711.45);
insert into product (id, name, brand, made_in, price) values (76, 'Salmon - Atlantic, Fresh, Whole', 'Strosin, Kunze and Jakubowski', 'Brazil', 909.65);
insert into product (id, name, brand, made_in, price) values (77, 'Milk Powder', 'Carroll and Sons', 'Brazil', 510.34);
insert into product (id, name, brand, made_in, price) values (78, 'Tumeric', 'Hayes, Miller and Mueller', 'Indonesia', 741.12);
insert into product (id, name, brand, made_in, price) values (79, 'Stock - Veal, White', 'Flatley and Sons', 'Afghanistan', 179.5);
insert into product (id, name, brand, made_in, price) values (80, 'Truffle Cups Green', 'Morar, Kulas and Stehr', 'Poland', 226.83);
insert into product (id, name, brand, made_in, price) values (81, 'Flour - Semolina', 'Hills Group', 'Azerbaijan', 540.21);
insert into product (id, name, brand, made_in, price) values (82, 'Pork - Liver', 'Waters-Moore', 'Sweden', 953.98);
insert into product (id, name, brand, made_in, price) values (83, 'Goulash Seasoning', 'Heathcote, Lindgren and Hermann', 'Nepal', 406.01);
insert into product (id, name, brand, made_in, price) values (84, 'Cookie Choc', 'Mayert-Ziemann', 'China', 17.41);
insert into product (id, name, brand, made_in, price) values (85, 'Cheese - La Sauvagine', 'Schuppe, Braun and Lindgren', 'United States', 202.78);
insert into product (id, name, brand, made_in, price) values (86, 'Longos - Burritos', 'Bins Inc', 'Poland', 741.35);
insert into product (id, name, brand, made_in, price) values (87, 'Mushroom - Enoki, Dry', 'Bergnaum, Cormier and Yundt', 'Armenia', 234.26);
insert into product (id, name, brand, made_in, price) values (88, 'Wine - Red, Cooking', 'Glover, Russel and Walter', 'Indonesia', 391.68);
insert into product (id, name, brand, made_in, price) values (89, 'Guinea Fowl', 'Sporer, Kovacek and Howe', 'United States', 347.17);
insert into product (id, name, brand, made_in, price) values (90, 'Napkin - Beverge, White 2 - Ply', 'Rempel-Boyle', 'China', 61.83);
insert into product (id, name, brand, made_in, price) values (91, 'Chocolate - Pistoles, White', 'Pfannerstill, Schroeder and Thiel', 'China', 468.96);
insert into product (id, name, brand, made_in, price) values (92, 'Pear - Asian', 'Bernhard and Sons', 'France', 161.59);
insert into product (id, name, brand, made_in, price) values (93, 'Tart Shells - Savory, 2', 'Bernhard-Cartwright', 'Thailand', 844.96);
insert into product (id, name, brand, made_in, price) values (94, 'Sour Puss Sour Apple', 'Sipes-Runolfsdottir', 'China', 266.58);
insert into product (id, name, brand, made_in, price) values (95, 'Tart Shells - Savory, 2', 'Braun, Hegmann and Carroll', 'Bosnia and Herzegovina', 126.02);
insert into product (id, name, brand, made_in, price) values (96, 'Mushroom Morel Fresh', 'Mayert Group', 'Poland', 700.08);
insert into product (id, name, brand, made_in, price) values (97, 'Bread Ww Cluster', 'Maggio-Hoppe', 'Czech Republic', 881.7);
insert into product (id, name, brand, made_in, price) values (98, 'Lambcasing', 'Kub, Lind and Crona', 'Ukraine', 32.92);
insert into product (id, name, brand, made_in, price) values (99, 'Muffin Mix - Corn Harvest', 'Lebsack Group', 'Portugal', 506.88);
insert into product (id, name, brand, made_in, price) values (100, 'Radish - Pickled', 'Daniel, Bechtelar and Walsh', 'China', 309.04);

