insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (1, 'Josias Forsdyke', 'Actuary', 'Male', 'Vila Chã', 84360.87);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (2, 'Bil MacLice', 'General Manager', 'Male', 'Novotroitsk', 90575.46);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (3, 'Antin Rodgers', 'Accounting Assistant III', 'Female', 'Lela', 33102.39);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (4, 'Scott Carville', 'Research Associate', 'Male', 'Rublëvo', 77503.81);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (5, 'Devonne Stealfox', 'Assistant Media Planner', 'Male', 'Unquillo', 66048.06);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (6, 'Lind Philpots', 'Environmental Tech', 'Male', 'Jarash', 37565.27);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (7, 'Briano Hadlee', 'Mechanical Systems Engineer', 'Female', 'Duanshen', 99177.51);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (8, 'Ab O''Skehan', 'Marketing Manager', 'Female', 'Banda Layung', 64516.96);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (9, 'Silvanus Stoffel', 'Software Consultant', 'Female', 'Guadalupe', 42475.05);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (10, 'Marisa Garey', 'Sales Associate', 'Male', 'Kiambu', 37506.35);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (11, 'Britni Salman', 'Nurse Practicioner', 'Female', 'Shuanglong', 74465.26);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (12, 'Sebastiano Palleske', 'Product Engineer', 'Female', 'Allen', 41826.64);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (13, 'Virgie Doniso', 'Web Developer I', 'Female', 'Karawatu', 2296.08);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (14, 'Rossie Windrum', 'Director of Sales', 'Male', 'San José de Colinas', 21286.62);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (15, 'Milena Eisold', 'Actuary', 'Male', 'Vilkaviskis', 48732.33);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (16, 'Codi Predohl', 'Junior Executive', 'Female', 'Aitape', 49361.28);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (17, 'Domenic Cathcart', 'Financial Advisor', 'Female', 'Örnsköldsvik', 36571.47);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (18, 'Lucila Sinney', 'Senior Financial Analyst', 'Female', 'Åkersberga', 68182.92);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (19, 'Sanderson Guinan', 'Geological Engineer', 'Male', 'Gabao', 77609.66);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (20, 'Karalee Titford', 'Senior Developer', 'Female', 'Langchi', 87251.85);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (21, 'Reiko Gentry', 'Automation Specialist III', 'Female', 'Malawa', 83740.23);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (22, 'Neala Cansfield', 'Mechanical Systems Engineer', 'Female', 'Damiao', 69965.66);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (23, 'Collette Scapelhorn', 'Account Coordinator', 'Female', 'Karangpawitan', 92199.92);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (24, 'Paula Torresi', 'Quality Control Specialist', 'Female', 'Tennō', 97389.04);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (25, 'Dagny Piotr', 'Account Representative II', 'Male', 'Kamogatachō-kamogata', 84609.99);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (26, 'Marga Reuss', 'Professor', 'Male', 'Corpus', 53465.7);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (27, 'Ode Heinz', 'Quality Control Specialist', 'Male', 'Makbon', 84741.85);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (28, 'Benji Kerner', 'Marketing Manager', 'Female', 'Baquero Norte', 67599.48);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (29, 'Evania Imbrey', 'Help Desk Technician', 'Male', 'Sigaozhuang', 10754.18);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (30, 'Odette Eathorne', 'Web Developer IV', 'Male', 'Pingsha', 99286.96);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (31, 'Shelly Haylock', 'VP Marketing', 'Male', 'Qiantang', 64923.67);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (32, 'Atalanta Taysbil', 'Senior Editor', 'Female', 'Tampere', 70950.98);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (33, 'Marja Adamovitz', 'Software Engineer II', 'Female', 'Reutov', 26788.6);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (34, 'Jervis MacClure', 'Compensation Analyst', 'Male', 'Kure', 3728.79);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (35, 'Zedekiah Dallyn', 'Environmental Specialist', 'Male', 'La Paz', 2719.73);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (36, 'Ivan Ruxton', 'Electrical Engineer', 'Male', 'Banjar Sembunggede', 65408.32);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (37, 'Fairlie Michallat', 'Research Nurse', 'Female', 'Albion', 26019.12);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (38, 'Shaw Worrall', 'Compensation Analyst', 'Male', 'Peoria', 10165.81);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (39, 'Lillian Ceaser', 'Desktop Support Technician', 'Female', 'Pakemitan', 32489.37);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (40, 'Eadith Larmuth', 'VP Quality Control', 'Male', 'Saint Louis', 36022.95);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (41, 'Olympe Fairbourne', 'Occupational Therapist', 'Male', 'Shikeng', 72991.6);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (42, 'Collen Avrashin', 'Software Consultant', 'Female', 'Gaoping', 25377.82);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (43, 'Humbert Laugheran', 'Research Assistant III', 'Female', 'Sidomulyo', 5362.47);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (44, 'Sherlock Pignon', 'VP Product Management', 'Male', 'Ketapang', 29979.17);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (45, 'Anjela Coorington', 'Database Administrator IV', 'Female', 'Gunungmanik', 65544.74);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (46, 'Gerhard Landy', 'Sales Associate', 'Female', 'Buzet', 62946.71);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (47, 'Brooks Northrop', 'Speech Pathologist', 'Female', 'Krajan Kedungsalam', 71618.7);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (48, 'Xylina Bantick', 'Software Consultant', 'Male', 'Chak Two Hundred Forty-Nine TDA', 1952.01);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (49, 'Guillemette Malone', 'Software Engineer I', 'Male', 'Khamyāb', 85981.51);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (50, 'Jenine Giscken', 'Executive Secretary', 'Female', 'Vilar', 46269.96);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (51, 'Sidoney Blackshaw', 'Junior Executive', 'Female', 'Margasana', 19496.72);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (52, 'Annora Tear', 'Software Engineer I', 'Male', 'Zongga', 5869.59);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (53, 'Marshal Dibden', 'Actuary', 'Male', 'Stockholm', 86656.15);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (54, 'Lane Kidney', 'Legal Assistant', 'Female', 'Mandal', 37230.67);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (55, 'Salomo Bircher', 'Account Coordinator', 'Male', 'Diepsloot', 83846.43);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (56, 'Adolphe Pachmann', 'Food Chemist', 'Female', 'Leidschendam', 71877.28);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (57, 'Abbie Eyam', 'Marketing Assistant', 'Female', 'Malakwal City', 30946.26);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (58, 'Kizzee Shillum', 'Staff Accountant I', 'Male', 'Huitong', 84719.88);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (59, 'Andrei Weich', 'VP Quality Control', 'Female', 'Al Nashmah', 46808.29);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (60, 'Warde Gerrish', 'Physical Therapy Assistant', 'Male', 'Horvati', 49614.04);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (61, 'Raviv Callaghan', 'Help Desk Operator', 'Male', 'Calancuasan Norte', 98650.65);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (62, 'Errick Louden', 'Environmental Specialist', 'Male', 'Nauchnyy Gorodok', 24835.45);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (63, 'Sarina Driuzzi', 'Nurse Practicioner', 'Male', 'Vale de São Cosme', 45942.86);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (64, 'Kali Heynen', 'Nurse', 'Male', 'Frankfurt am Main', 34926.76);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (65, 'Gerald Brolly', 'Research Nurse', 'Male', 'Xian’an', 17049.43);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (66, 'Retha Jacobsson', 'Programmer II', 'Male', 'Enköping', 19475.56);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (67, 'Eleanore McDaid', 'Biostatistician IV', 'Male', 'Clogherhead', 45286.13);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (68, 'Nevsa Boanas', 'Graphic Designer', 'Male', 'Kaduela', 15785.35);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (69, 'Madelene Borles', 'Design Engineer', 'Male', 'Cimenga', 28988.8);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (70, 'Mommy Bretherick', 'VP Product Management', 'Male', 'Denver', 9585.1);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (71, 'Rosana Castana', 'Assistant Media Planner', 'Female', 'Penteado', 25229.46);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (72, 'Ruthi D''Aguanno', 'Teacher', 'Male', 'Kon Dơng', 17859.62);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (73, 'Oralle Cavaney', 'Account Executive', 'Female', 'El Coco', 35538.85);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (74, 'Lothaire Camel', 'Human Resources Assistant III', 'Male', 'Naru', 55009.52);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (75, 'Arie Halso', 'Statistician I', 'Female', 'Kedung', 39151.99);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (76, 'Kayne McNeely', 'Mechanical Systems Engineer', 'Male', 'Daugai', 15187.78);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (77, 'Jody De Carlo', 'VP Product Management', 'Female', 'Serzedo', 68408.82);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (78, 'Eirena Pallasch', 'Automation Specialist III', 'Male', 'Sawaengha', 28711.68);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (79, 'Thekla Windram', 'Product Engineer', 'Female', 'Quimperlé', 90987.49);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (80, 'Kailey Teck', 'Librarian', 'Female', 'Binuangan', 80034.74);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (81, 'Dorena Newlands', 'Geologist II', 'Male', 'Kenamoen', 8005.41);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (82, 'Leda Currom', 'Editor', 'Female', 'Palangkaraya', 66616.25);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (83, 'Betteann Pipworth', 'Human Resources Assistant IV', 'Female', 'Huanghu', 95101.92);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (84, 'Jenn Hindsberg', 'Budget/Accounting Analyst III', 'Male', 'Songgai', 18666.58);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (85, 'Ceil Wharton', 'Office Assistant II', 'Female', 'Tikhvin', 4389.49);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (86, 'Kamillah Perri', 'GIS Technical Architect', 'Male', 'Zvezdara', 96102.11);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (87, 'Maurine Vials', 'Director of Sales', 'Male', 'Jandaia do Sul', 23651.91);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (88, 'Cesar Bracci', 'Actuary', 'Male', 'Tsul-Ulaan', 44175.71);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (89, 'Farica Locard', 'VP Marketing', 'Female', 'Benito Juarez', 97326.36);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (90, 'Dot Addicote', 'Senior Financial Analyst', 'Female', 'East Angus', 45019.9);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (91, 'Tedie Friese', 'Clinical Specialist', 'Female', 'Dongfanghong', 59460.06);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (92, 'Torie Divell', 'Software Consultant', 'Male', 'Santa Cruz', 40818.64);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (93, 'Hervey Donnan', 'Assistant Manager', 'Female', 'Centre de Flacq', 41034.83);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (94, 'Milicent Potte', 'Executive Secretary', 'Male', 'Łąck', 1368.52);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (95, 'Alie Ewin', 'Electrical Engineer', 'Female', 'Kuczbork-Osada', 87546.77);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (96, 'Devondra McAnellye', 'Assistant Professor', 'Male', 'Kassala', 13639.44);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (97, 'Nicolette Gyver', 'Senior Cost Accountant', 'Male', 'Kuntong', 24442.03);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (98, 'Kimberley Croxon', 'Systems Administrator II', 'Male', 'Kang-neung', 25866.28);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (99, 'Molli Baack', 'Internal Auditor', 'Male', 'Mache', 71626.41);
insert into person (ID, FULL_NAME, JOB, GENDER, CITY, SALARY) values (100, 'Sax Bouda', 'Electrical Engineer', 'Male', 'Bitica', 45265.09);
